### ISSUE TITLE
`exchange` cannot return a result different than the one sent away

### ISSUE THREAD

**Issue by DanySK** [Collektive/collektive#175]
@angelacorte my understanding is that `exchange`, similarly to `share`, can yield a result different than the messages sent away, yet it can't in collektive -- correct?

**Comment by angelacorte** [comment]
@DanySK correct, we explored that way (the one which yields a result with a different type than the messages sent) but agreed that at the moment we shouldn't need it. 
If I remember right we said that approximately the 90% of the times it was expected to yield the same type, for this reason we opted not to implement it yet.

**Comment by DanySK** [comment]
@angelacorte okay. Not a priority for your work I guess, but I think that's about time to have it full fledged
