### ISSUE TITLE
Debug-friendly code generation

### ISSUE THREAD

**Issue by DanySK** [Collektive/collektive#337]
The plugin currently generates stuff like:

```kotlin
alignedOn("function name") {
    actualCode
}
```

when `actualCode` contains aggregate code. I propose to generate instead:
```kotlin
alignRaw("function name")
val mangled = actualCode
dealign()
return mangled
```

Otherwise, debugging can be hell:
<img width="392" alt="image" src="https://github.com/Collektive/collektive/assets/1991673/7e689c60-6e0a-487f-8deb-16129039df38">

**Comment by nicolasfara** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New alignment operation in Collektive](https://trello.com/c/klegG1My/1-new-alignment-operation-in-collektive)
