### ISSUE TITLE
Lowering error when compiling complex class

### ISSUE THREAD

**Issue by DanySK** [Collektive/collektive#339]
Checkout this tag: https://github.com/angelacorte/vmc-experiments/releases/tag/collektive-bug-lowering to reproduce
[ir-error.log](https://github.com/Collektive/collektive/files/15247083/ir-error.log)

**Comment by DanySK** [comment]
commenting out `spawn(absoluteDestination)` makes the compilation work

**Comment by DanySK** [comment]
@angelacorte can you give it a spin?

**Comment by angelacorte** [comment]
The error cannot be reproduced with version 10.1.1 of Collektive and Kotlin 2
