### ISSUE TITLE
Frontend compiler plugin raises a warning but the IDE does not show anything

### ISSUE THREAD

**Issue by nicolasfara** [Collektive/collektive#507]
I was messing around with Collektive version `10.3.2` and I noticed that warning produced during the compilation are not shown within the IDE (IntelliJ)

The following code:

```kt
private fun Aggregate<Int>.foo() {
    align(1)
    for (i in 0..10) {
        neighboring(i)
    }
}
```

should (and does) generate a warning because of the `align` call and no `alignOn` inside the loop. Great.
However, no warnings are raised in the IDE... A picture as follows:

![image](https://github.com/user-attachments/assets/4d7feea4-5587-4d98-bbab-800069541035)

@FreshMag could you investigate this issue? From what I understood, with the frontend, we can raise a warning also inside the IDE.

Moreover, when compiling this is the produced output:

```
e: warnings found and -Werror specified
w: file:///home/nicolas/Documents/repos/collektive/deleteme-wasm/src/wasmWasiMain/kotlin/TestWasmCollektive.kt:28:5 [DOT_CALL_WARNING] Warning: 'align' method should not be explicitly used
w: file:///home/nicolas/Documents/repos/collektive/deleteme-wasm/src/wasmWasiMain/kotlin/TestWasmCollektive.kt:28:5 Warning: 'align' method should not be explicitly used
w: file:///home/nicolas/Documents/repos/collektive/deleteme-wasm/src/wasmWasiMain/kotlin/TestWasmCollektive.kt:30:9 [DOT_CALL_WARNING] Warning: aggregate function 'neighboring' called inside a loop with no manual alignment operation
w: file:///home/nicolas/Documents/repos/collektive/deleteme-wasm/src/wasmWasiMain/kotlin/TestWasmCollektive.kt:30:9 Warning: aggregate function 'neighboring' called inside a loop with no manual alignment operation
```

I cannot understand why the logs are repeated. Could you fix also this issue?

**Comment by FreshMag** [comment]
I have not yet looked into integrating the plugin’s frontend with the IDE (IntelliJ in this case). Currently, the diagnostics generated by the plugin are only displayed during compilation.

Regarding the duplication of warning messages, I will investigate that as soon as possible. What are the steps required to reproduce this output?

**Comment by nicolasfara** [comment]
> I have not yet looked into integrating the plugin’s frontend with the IDE (IntelliJ in this case). Currently, the diagnostics generated by the plugin are only displayed during compilation.
> 
> Regarding the duplication of warning messages, I will investigate that as soon as possible. What are the steps required to reproduce this output?

Having the warning inside the IDE rather than during the compilation would be interesting.

I further investigated the duplicate warning, and the double warning does not occur in external projects, so I guess that the duplication occurs only inside the codebase.

Could you investigate how to attach the warning inside the IDE?

**Comment by FreshMag** [comment]
Ok, I will check on it
