### ISSUE TITLE
Alignment problem?

### ISSUE THREAD

**Issue by nicolasfara** [Collektive/collektive#51]
Considering the following AC program (no-sense):

```kotlin
val result = aggregate {
    neighbouring(10) // path -> [neighbouring] = 10
    sharing(0) {
        neighbouring(20) // path -> [sharing, neighbouring] = 20
    } // path -> [sharing] = Field(...)
    neighbouring(30) // path -> [neighbouring] = 30
    5
}
```

In this program we have 4 points of alignment, right?

If so, the output result from the `aggregate` computation is wrong.  
The produced output is the following:

```
AggregateResult(
    result=5,
    toSend={Path(path=[neighbouring])=30, Path(path=[sharing, neighbouring])=20, Path(path=[sharing])=FieldImpl(...), messages={IntId(...)=20})},
    newState={Path(path=[sharing])=FieldImpl(...), messages={IntId(...)=20})}
)
```
In particular, the `toSend` attribute (which is used to align with the neighbors, right?) has only 3 paths:

  - `Path(path=[neighbouring])=30`
  - `Path(path=[sharing, neighbouring])=20`
  - `Path(path=[sharing])=FieldImpl(...)`

As can be seen, the first alignment on `neighbouring(10)` is lost. This is due to the fact that the key of the map is the same for the first and the last `neighbouring`

The expected result should be:

  * `Path(path=[neighbouring-1])=10`
  * `Path(path=[sharing, neighbouring])=20`
  * `Path(path=[sharing])=FieldImpl(...)`
  * `Path(path=[neighbouring-2])=30`

Is it right?

Generalizing, having the same operator without a nested aggregate operator, only the last call is aligned due to the same key determined by the path.

Another thing not clear to me is why we have `Path(path=[sharing])=FieldImpl(...)` which aligns on a `Field` instead of a value.  
Is this right or a bug?

@DanySK @cric96 @ElisaTronetti could you provide me some feedback about the above considerations? Am I right, or I have missed something?

**Comment by DanySK** [comment]
this is a bug. 

Result should be like:

```kotlin
val result = aggregate {
    neighbouring(10) // path -> [neighbouring] = 10
    sharing(0) {
        neighbouring(20) // path -> [neighbouring, sharing, neighbouring] = 20
    } // path -> [neighbouring, sharing] = Field(...)
    neighbouring(30) // path -> [neighbouring, neighbouring] = 30
    5
}
```

**Comment by nicolasfara** [comment]
Ok.

The following can be also a valid representation? Because I think is more feasible to implement it in the compiler plugin.

```kotlin
val result = aggregate {
    neighbouring(10) // path -> [neighbouring.1] = 10
    sharing(0) {
        neighbouring(20) // path -> [sharing.1, neighbouring.2] = 20
    } // path -> [sharing.1] = Field(...)
    neighbouring(30) // path -> [neighbouring.3] = 30
    5
}

**Comment by DanySK** [comment]
yes it is -- even a better one
